import Foundation


/**
 * [The Mpesa Payment object](https://falu.io)
 */
public class Mpesa: Codable{
    /**
     * Type of payment
     */
    public var type: String? = nil

    /**
     * Reference the payment was made in.
     */
    public var reference: String? = nil

    /**
     * Phone number that made the payment, in E.164 format.
     */
    public var phone: String? = nil

    /**
     * Name of the entity making or that made the payment.
     */
    public var payer: String? = nil

    /**
     * The target business short code
     */
    public var businessShortCode: String? = nil

    /**
     * Unique transaction identifier generated by Mpesa.
     * Only populated for completed transactions.
     */
    public var receipt: String? = nil

    public enum CodingKeys: String, CodingKey{
        case type
        case reference
        case phone
        case payer
        case businessShortCode = "business_short_code"
        case receipt
    }
}
