import Foundation


/**
 * [The Mpesa Payment object](https://falu.io)
 */
class Mpesa: Codable{
    /**
       * Type of payment
       */
      var type: PaymentType? = nil

      /**
       * Reference the payment was made in.
       */
      var reference: String? = nil

      /**
       * Phone number that made the payment, in E.164 format.
       */
      var phone: String? = nil

      /**
       * Name of the entity making or that made the payment.
       */
      var payer: String? = nil

      /**
       * The target business short code
       */
      var businessShortCode: String? = nil

      /**
       * Unique transaction identifier generated by Mpesa.
       * Only populated for completed transactions.
       */
      var receipt: String? = nil
}
