import Foundation

/**
 * Represents details about the statement used for an evaluation.
 */
class EvaluationStatement: Codable{
    /**
     * Represents the kind of provider used for a statement in an evaluation.
     */
    var provider: StatementProvider? = nil

    /**
     * Email found in the statement.
     */
    var email: String? = nil

    /**
     * Name found in the statement
     */
    var name: String? = nil

    /**
     * Phone number found in the statement.
     */
    var phone: String? = nil

    /**
     * Time at which the statement was generated by the provider.
     */
    var generated: Date? = nil

    /**
     * The period of the statement
     */
    var period: Period? = nil
}


struct Period: Codable {
    var start: Date?
    var end: Date?
}
