name: Build and Test

on:
  push:
    tags:
      - '*'
    paths-ignore: # do not trigger for changes in docs
      - docs/**
      - README.md
      - CHANGELOG.md
      - LICENSE.md
  pull_request:
    branches: [ main ]
    paths-ignore: # do not trigger for changes in docs
      - docs/**
      - README.md
      - CHANGELOG.md
      - LICENSE.md

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Resolve dependencies
      run: swift package resolve

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
